name: Build browser tree and data
on:
  push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Run script file
      run: |
         bash viewer/*.sh
      shell: bash 
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: LaTexCompiler
        message: 'Compiled LaTeX into PDF, updated README'
        add: '["*.pdf","*md"]'
