name: Build browser tree and data
on:
  schedule:    
  - cron: "*/30 * * * *"
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Run script file
      run: |
         bash viewer/*.sh
      shell: bash 
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: LaTexCompiler
        message: 'Save json tree'
        add: 'viewer/list.json'
